# -*- coding: utf-8 -*-
"""
CodeSearcher For Don't Starve Together Players: Special Edition 1.1

With inside Codebase

Created on Thu May  7 14:34:30 2020

@author: Steve.D.Jobs

Copyright (c) 2020 Steve D. J..All rights reserved.
"""
from pandas import DataFrame

print("Copyright (c) 2020 Steve D. J..All rights reserved.\n")
print("欢迎使用CodeSearcher For Don't Starve Together: Special Edition 1.1!\n")

data = [['cutgrass','草'],
['twigs','树枝'],
['log','木头'],
['charcoal','木炭'],
['ash','灰'],
['cutreeds','采下的芦苇'],
['lightbulb','荧光果'],
['petals','花瓣'],
['petals_evil','噩梦花瓣'],
['pinecone','松果'],
['foliage','叶子'],
['cutlichen','摘下的苔藓'],
['wormlight','虫子果'],
['lureplantbulb','食人花种子'],
['flint','燧石'],
['nitre','硝石'],
['redgem','红宝石'],
['bluegem','蓝宝石'],
['purplegem','紫宝石'],
['greengem','绿宝石'],
['orangegem','橙宝石'],
['yellowgem','黄宝石'],
['rocks','岩石'],
['goldnugget','黄金'],
['thulecite','铥矿石'],
['thulecite_pieces','铥矿碎片'],
['rope','绳子'],
['boards','木板'],
['cutstone','石砖'],
['papyrus','纸'],
['houndstooth','犬牙'],
['pigskin','猪皮'],
['manrabbit_tail','兔人尾巴'],
['silk','蜘蛛丝'],
['spidergland','蜘蛛腺体'],
['spidereggsack','蜘蛛卵'],
['beardhair','胡子'],
['beefalowool','牛毛'],
['honeycomb','蜂巢'],
['stinger','蜂刺'],
['walrus_tusk','海象牙'],
['feather_crow','乌鸦羽毛'],
['feather_robin','红雀羽毛'],
['feather_robin_winter','雪雀羽毛'],
['horn','牛角'],
['tentaclespots','触手皮'],
['trunk_summer','夏象鼻'],
['trunk_winter','冬象鼻'],
['slurtleslime','蜗牛龟粘液'],
['slurtle_shellpieces','蜗牛龟壳片'],
['butterflywings','蝴蝶翅膀'],
['mosquitosack','蚊子血囊'],
['slurper_pelt','啜食者皮'],
['minotaurhorn','远古守护者角'],
['deerclops_eyeball','巨鹿眼球'],
['lightninggoathorn','闪电羊角'],
['glommerwings','格罗姆翅膀'],
['glommerflower','格罗姆花'],
['glommerfuel','格罗姆燃料'],
['livinglog','活木头'],
['nightmarefuel','噩梦燃料'],
['gears','齿轮'],
['transistor','电子元件'],
['marble','大理石'],
['boneshard','硬骨头'],
['ice','冰'],
['poop','便便'],
['guano','鸟粪'],
['dragon_scales','蜻蜓鳞片'],
['goose_feather','鹿鸭羽毛'],
['coontail','浣熊尾巴'],
['bearger_fur','熊皮'],
['axe','斧子'],
['goldenaxe','黄金斧头'],
['lucy','露西斧子'],
['hammer','锤子'],
['pickaxe','镐'],
['goldenpickaxe','黄金镐'],
['shovel','铲子'],
['goldenshovel','黄金铲子'],
['pitchfork','草叉'],
['razor','剃刀'],
['bugnet','捕虫网'],
['fishingrod','鱼竿'],
['multitool_axe_pickaxe','多功能工具'],
['cane','行走手杖'],
['trap','陷阱'],
['birdtrap','鸟陷阱'],
['trap_teeth','牙齿陷阱'],
['trap_teeth_maxwell','麦斯威尔的牙齿陷阱'],
['backpack','背包'],
['piggyback','猪皮包'],
['krampus_sack','坎普斯背包'],
['umbrella','雨伞'],
['grass_umbrella','草伞'],
['heatrock','保温石'],
['bedroll_straw','草席卷'],
['bedroll_furry','毛皮铺盖'],
['torch','火炬'],
['lantern','提灯'],
['pumpkin_lantern','南瓜灯'],
['compass','指南针'],
['fertilizer','化肥'],
['firesuppressor','灭火器'],
['sewing_kit','缝纫工具包'],
['spear','矛'],
['boomerang','回旋镖'],
['tentaclespike','狼牙棒'],
['blowdart_pipe','吹箭'],
['blowdart_sleep','麻醉吹箭'],
['blowdart_fire','燃烧吹箭'],
['hambat','火腿短棍'],
['nightsword','暗影剑'],
['batbat','蝙蝠棒'],
['ruins_bat','远古短棒'],
['spear_wathgrithr','瓦丝格雷斯矛'],
['panflute','排箫'],
['onemanband','独奏乐器'],
['gunpowder','火药'],
['beemine','蜜蜂地雷'],
['bell','铃'],
['amulet','红色护身符'],
['blueamulet','蓝色护身符'],
['purpleamulet','紫色护身符'],
['yellowamulet','黄色护身符'],
['orangeamulet','橙色护身符'],
['greenamulet','绿色护身符'],
['nightmare_timepiece','铥矿奖章'],
['icestaff','冰魔杖'],
['firestaff','火魔杖'],
['telestaff','传送魔杖'],
['orangestaff','橙色魔杖'],
['strawhat','草帽'],
['flowerhat','花环'],
['greenstaff','绿色魔杖'],
['yellowstaff','黄色魔杖'],
['diviningrod','探矿杖'],
['book_birds','召唤鸟的书'],
['book_tentacles','召唤触手的书'],
['book_gardening','催生植物的书'],
['book_sleep','催眠的书'],
['book_brimstone','召唤闪电的书'],
['waxwelljournal','麦斯威尔的日志'],
['abigail_flower','阿比盖尔之花'],
['balloons_empty','空气球'],
['balloon','气球'],
['lighter','薇洛的打火机'],
['chester_eyebone','切斯特骨眼'],
['featherfan','羽毛扇'],
['staff_tornado','龙卷风魔杖'],
['nightstick','夜棍'],
['beefalohat','牛毛帽'],
['featherhat','羽毛帽'],
['footballhat','猪皮帽'],
['tophat','高礼帽'],
['earmuffshat','兔耳罩'],
['winterhat','冬帽'],
['minerhat','矿工帽'],
['spiderhat','蜘蛛帽'],
['beehat','蜂帽'],
['walrushat','海象帽'],
['slurtlehat','蜗牛帽子'],
['bushhat','丛林帽'],
['ruinshat','远古王冠'],
['rainhat','防雨帽'],
['icehat','冰帽'],
['watermelonhat','西瓜帽'],
['catcoonhat','浣熊帽'],
['wathgrithrhat','瓦丝格雷斯帽'],
['armorwood','木盔甲'],
['campfire','营火'],
['firepit','石头营火'],
['armorgrass','草盔甲'],
['armormarble','大理石盔甲'],
['armor_sanity','夜魔盔甲'],
['armorsnurtleshell','蜗牛龟盔甲'],
['armorruins','远古盔甲'],
['sweatervest','小巧背心'],
['trunkvest_summer','夏日背心'],
['trunkvest_winter','寒冬背心'],
['armorslurper','饥饿腰带'],
['raincoat','雨衣'],
['webberskull','韦伯头骨'],
['molehat','鼹鼠帽'],
['armordragonfly','蜻蜓盔甲'],
['beargervest','熊背心'],
['eyebrellahat','眼睛帽'],
['reflectivevest','反射背心'],
['hawaiianshirt','夏威夷衬衫'],
['coldfire','冷火'],
['coldfirepit','石头冷火'],
['cookpot','锅'],
['icebox','冰箱'],
['winterometer','寒冰温度计'],
['rainometer','雨量计'],
['slow_farmplot','一般农田'],
['fast_farmplot','高级农田'],
['siestahut','午睡小屋'],
['tent','帐篷'],
['homesign','路牌'],
['birdcage','鸟笼'],
['meatrack','晾肉架'],
['lightning_rod','避雷针'],
['pottedfern','盆栽'],
['nightlight','暗夜照明灯'],
['nightmarelight','影灯'],
['researchlab','科学机器'],
['researchlab2','炼金术引擎'],
['researchlab3','阴影操纵者'],
['researchlab4','灵子分解器'],
['treasurechest','木箱'],
['skullchest','骷髅箱'],
['pandoraschest','华丽的箱子'],
['minotaurchest','大华丽的箱子'],
['wall_hay_item','草墙'],
['wall_wood_item','木墙'],
['wall_stone_item','石墙'],
['wall_ruins_item','铥墙'],
['wall_hay','地上的草墙'],
['wall_wood','地上的木墙'],
['wall_stone','地上的石墙'],
['wall_ruins','地上的铥墙'],
['pighouse','猪房'],
['rabbithole','兔房'],
['mermhouse','鱼人房'],
['resurrectionstatue','肉块雕像'],
['resurrectionstone','复活石'],
['ancient_altar','远古祭坛'],
['ancient_altar_broken','损坏的远古祭坛'],
['telebase','传送核心'],
['gemsocket','宝石看台'],
['eyeturret','固定在地上的眼睛炮塔'],
['eyeturret_item','可带走的眼睛炮塔'],
['cave_exit','洞穴出口'],
['turf_woodfloor','木地板'],
['turf_carpetfloor','地毯地板'],
['turf_checkerfloor','棋盘地板'],
['adventure_portal','冒险之门'],
['rock_light','火山坑'],
['gravestone','墓碑'],
['mound','坟墓土堆'],
['skeleton','人骨'],
['houndbone','狗骨头'],
['animal_track','动物足迹'],
['dirtpile','可疑的土堆'],
['pond','池塘'],
['pond_cave','洞穴池塘'],
['pighead','猪头棍'],
['mermhead','鱼头棍'],
['pigtorch','猪火炬'],
['rabbithole','兔子洞'],
['beebox','蜂箱'],
['beehive','野生蜂窝'],
['wasphive','杀人蜂窝'],
['spiderhole','洞穴蜘蛛洞'],
['walrus_camp','海象窝'],
['tallbirdnest','高鸟窝'],
['houndmound','猎犬丘'],
['slurtlehole','蜗牛窝'],
['batcave','蝙蝠洞'],
['monkeybarrel','猴子桶'],
['spiderden','蜘蛛巢穴'],
['molehill','鼹鼠丘'],
['catcoonden','浣熊洞'],
['rock1','带硝石的岩石'],
['rock2','带黄金的岩石'],
['rock_flintless','只有石头的岩石'],
['stalagmite_full','大圆洞穴石头'],
['stalagmite_med','中圆洞穴石头'],
['stalagmite_low','小圆洞穴石头'],
['stalagmite_tall_full','大高洞穴石头'],
['stalagmite_tall_med','中高洞穴石头'],
['stalagmite_tall_low','小高洞穴石头'],
['rock_ice','冰石'],
['ruins_statue_head','远古头像'],
['ruins_statue_mage','远古法师雕像'],
['marblepillar','大理石柱子'],
['marbletree','大理石树'],
['statueharp','竖琴雕像'],
['basalt','玄武岩'],
['basalt_pillar','高玄武岩'],
['insanityrock','猪王矮柱石'],
['sanityrock','猪王高柱石'],
['ruins_chair','远古椅子'],
['ruins_vase','远古花瓶'],
['ruins_table','远古桌子'],
['statuemaxwell','麦斯威尔雕像'],
['statueglommer','格罗门雕像'],
['relic','废墟'],
['ruins_rubble','损毁的废墟'],
['bishop_nightmare','损坏的雕像'],
['rook_nightmare','损坏的战车'],
['knight_nightmare','损坏的骑士'],
['chessjunk1','损坏的机械1'],
['chessjunk2','损坏的机械2'],
['carrot','胡萝卜'],
['chessjunk3','损坏的机械3'],
['teleportato_ring','环状传送机零件'],
['teleportato_box','盒状传送机零件'],
['teleportato_crank','曲柄状传送机零件'],
['teleportato_potato','球状传送机零件'],
['teleportato_base','传送机零件底座'],
['teleportato_checkmate','传送机零件底座'],
['wormhole','虫洞'],
['wormhole_limited_1','被限制的虫洞'],
['stafflight','小星星'],
['treasurechest_trap','箱子陷阱'],
['icepack','冰包'],
['dragonflychest','蜻蜓箱子'],
['carrot_cooked','熟胡萝卜'],
['cookedmonstermeat','熟怪物肉'],
['monstermeat_dried','干怪物肉'],
['plantmeat','食人花肉'],
['plantmeat_cooked','熟食人花肉'],
['honey','蜂蜜'],
['butter','黄油'],
['butterflymuffin','蝴蝶松饼'],
['frogglebunwich','蛙腿三明治'],
['bird_egg','蛋'],
['bird_egg_cooked','熟蛋'],
['rottenegg','烂蛋'],
['tallbirdegg','高鸟蛋'],
['tallbirdegg_cooked','熟高鸟蛋'],
['tallbirdegg_cracked','孵化的高鸟蛋'],
['fish','鱼'],
['fish_cooked','熟鱼'],
['eel','鳗鱼'],
['eel_cooked','熟鳗鱼'],
['froglegs','蛙腿'],
['froglegs_cooked','熟蛙腿'],
['batwing','蝙蝠翅膀'],
['batwing_cooked','熟蝙蝠翅膀'],
['trunk_cooked','熟象鼻'],
['mandrake','曼德拉草'],
['cookedmandrake','熟曼德拉草'],
['honeyham','蜜汁火腿'],
['dragonpie','火龙果派'],
['taffy','太妃糖'],
['pumpkincookie','南瓜饼'],
['kabobs','肉串'],
['powcake','芝士蛋糕'],
['mandrakesoup','曼德拉草汤'],
['baconeggs','鸡蛋火腿'],
['bonestew','肉汤'],
['perogies','半圆小酥饼'],
['wetgoop','湿腻焦糊'],
['ratatouille','蹩脚的炖菜'],
['fruitmedley','水果拼盘'],
['fishtacos','玉米饼包炸鱼'],
['waffles','华夫饼'],
['turkeydinner','火鸡正餐'],
['fishsticks','炸鱼排'],
['stuffedeggplant','酿茄子'],
['honeynuggets','蜂蜜蜜金砖'],
['meatballs','肉丸'],
['jammypreserves','果酱蜜饯'],
['monsterlasagna','怪物千层饼'],
['unagi','鳗鱼料理'],
['bandage','蜂蜜绷带'],
['healingsalve','治疗药膏'],
['dragonflychest','蜻蜓箱子'],
['carrot_cooked','熟胡萝卜'],
['cave_banana_tree','洞穴香蕉树'],
['mushtree_small','小蘑菇树'],
['livingtree','活树'],
['deciduoustree','橡树'],
['deciduoustree_tall','高橡树'],
['deciduoustree_short','矮橡树'],
['red_mushroom','红蘑菇'],
['green_mushroom','绿蘑菇'],
['blue_mushroom','蓝蘑菇'],
['mushtree_tall','高蘑菇树'],
['mushtree_medium','中蘑菇树'],
['rabbit','兔子'],
['perd','火鸡'],
['crow','乌鸦'],
['robin','红鸟'],
['robin_winter','蓝鸟'],
['butterfly','蝴蝶'],
['fireflies','萤火虫'],
['bee','蜜蜂'],
['killerbee','杀人蜂'],
['flower_cave','单朵洞穴花'],
['flower_cave_double','双朵洞穴花'],
['flower_cave_triple','三朵洞穴花'],
['tumbleweed','风滚草'],
['cactus','仙人掌'],
['cactus_flower','仙人掌花'],
['marsh_plant','水塘边小草'],
['pond_algae','水藻'],
['flies','苍蝇'],
['mosquito','蚊子'],
['frog','青蛙'],
['beefalo','牛'],
['babybeefalo','小牛'],
['lightninggoat','闪电羊'],
['pigman','猪人'],
['pigguard','猪守卫'],
['bunnyman','兔人'],
['merm','鱼人'],
['spider_hider','洞穴蜘蛛'],
['spider_spitter','喷射蜘蛛'],
['spider','地面小蜘蛛'],
['spider_warrior','地面绿蜘蛛'],
['spiderqueen','蜘蛛女王'],
['spider_dropper','白蜘蛛'],
['hound','猎狗'],
['firehound','火狗'],
['icehound','冰狗'],
['tentacle','触手'],
['tentacle_garden','巨型触手'],
['leif','树人'],
['leif_sparse','稀有树人'],
['walrus','海象'],
['little_walrus','小海象'],
['smallbird','小高鸟'],
['teenbird','青年高鸟'],
['tallbird','高鸟'],
['worm','远古虫子'],
['abigail','阿比盖尔'],
['ghost','幽灵'],
['koalefant_summer','夏象'],
['koalefant_winter','冬象'],
['penguin','企鹅'],
['slurtle','蜗牛龟'],
['snurtle','黏糊虫'],
['bat','蝙蝠'],
['rocky','石龙虾'],
['monkey','猴子'],
['slurper','吸缀食者'],
['buzzard','秃鹫'],
['mole','鼹鼠'],
['catcoon','浣熊'],
['knight','发条骑士'],
['bishop','主教'],
['rook','战车'],
['crawlinghorror','爬行暗影怪'],
['terrorbeak','尖嘴暗影怪'],
['deerclops','巨鹿'],
['minotaur','远古守护者'],
['shadowwaxwell','麦斯威尔黑影小人'],
['krampus','坎普斯'],
['glommer','格鲁姆'],
['chester','切斯特'],
['lureplant','食人花'],
['eyeplant','食人花眼睛'],
['bigfoot','大脚'],
['pigking','猪王'],
['moose','鹿鸭'],
['mossling','小鸭'],
['dragonfly','蜻蜓龙蝇'],
['warg','座狼'],
['bearger','熊'],
['birchnutdrake','坚果鸭'],
['mooseegg','鹿鸭蛋'],
['bernie_inactive','伯尼熊'],
['sewing_tape','可靠的胶布'],
['mermhat','渔人面具'],
['saltrock','盐晶'],
['driftwood_log','浮木桩'],
['spoiled_fish','变质的鱼'],
['spoiled_fish_small','坏掉的小鱼'],
['malbatross_beak','邪天翁喙'],
['malbatross_feather','邪天翁羽毛'],
['multiplayer_portal_moonrock_constr_plans','传送门设备'],
['moonrockidol','月亮摇滚偶像'],
['moonrockseed','天体球'],
['spore_small','绿色孢子'],
['spore_medium','红色孢子'],
['spore_tall','蓝色孢子'],
['waxpaper','蜡纸'],
['beeswax','蜂蜡'],
['moonrocknugget','月亮石'],
['opalpreciousgem','彩虹宝石'],
['moonrockcrater','火山口月石'],
['redmooneye','红色月石'],
['orangemooneye','橙色月石'],
['yuellowmooneye','黄色月棱镜'],
['greenmooneye','绿色月棱镜'],
['bluemooneye','蓝色月棱镜'],
['purplemooneye','紫色月石'],
['townportaltalisman','砂石'],
['phlegm','脓鼻涕'],
['steelwool','钢绒'],
['feather_canary','橙黄羽毛'],
['deer_antler1/2/3','鹿角（无眼鹿的3种鹿角）1/2/3'],
['klaussackkey','牡鹿角（克劳斯钥匙）'],
['lavae_egg','岩浆蛋'],
['lavae_cocoon','冷冻虫卵'],
['lavae_tooth','岩浆牙'],
['shadowheart','暗影之心'],
['cookiecuttershell','饼干切割机壳'],
['shroom_skin','魔蛤皮'],
['fossil_piece或fossil_piece_clean','化石碎片'],
['pocket_scale','弹簧秤'],
['oceanfishingrod','海钓竿'],
['fishingnet','渔网'],
['mast_item','桅杆套装'],
['mast_malbatross_item','飞翼风帆套装'],
['malbatross_feathered_weave','羽毛帆布'],
['oar','船桨'],
['oar_driftwood','浮木桨'],
['oceanfishingbobber_ball','木球浮标'],
['oceanfishingbobber_ball_tacklesketch','木球浮标广告'],
['oceanfishingbobber_canary','番红花羽浮标'],
['oceanfishingbobber_canary_tacklesketch','番红花羽浮标广告'],
['oceanfishingbobber_goose','鹅羽浮标'],
['oceanfishingbobber_goose_tacklesketch','鹅羽浮标广告'],
['oceanfishingbobber_malbatross','邪天翁羽浮标'],
['oceanfishingbobber_malbatross_tacklesketch','邪天翁羽浮标广告'],
['oceanfishingbobber_oval','硬物浮标'],
['oceanfishingbobber_oval_tacklesketch','硬物浮标广告'],
['oceanfishingbobber_robin','红羽浮标'],
['oceanfishingbobber_robin_tacklesketch','红羽浮标广告'],
['miniflare','信号'],
['saltbox','盐盒'],
['featherpencil','羽毛笔'],
['saddlehorn','鞍角'],
['saddle_basic','上鞍'],
['saddle_war','战争牛鞍'],
['saddle_race','薄弱牛鞍'],
['brush','洗刷'],
['reviver','复活之心'],
['lifeinjector','强心针'],
['waterballoon','水球'],
['bundlewrap','捆绑包装纸'],
['bundle','捆绑成束的补给'],
['minifan','回旋扇'],
['mapscroll','地图卷轴'],
['waxwelljournal','暗影法典'],
['thurible','暗影香炉'],
['nightstick','晨星'],
['whip','三尾猫鞭'],
['opalstaff','访月者手杖'],
['sporecloud','毒孢子云'],
['mushroombomb','蘑菇炸弹'],
['mushroombomb_dark','悲剧蘑菇炸弹'],
['kelphat','海花冠'],
['cookiecutterhat','饼干切割机帽子'],
['red_mushroomhat','红绿蓝色乐趣帽子蘑菇'],
['goggleshat','时髦目镜'],
['deserthat','沙漠目镜'],
['armorskeleton','白骨盔甲'],
['armorslurper','饥饿腰带'],
['cabbagerolls','白菜卷'],
['kelp','海带叶'],
['kelp_dried','干海带叶'],
['kelp_cooked','熟海带叶'],
['berries','浆果'],
['berries_cooked','烤浆果'],
['berries_juicy','多汁浆果'],
['berries_juicy_cooked','多汁烤浆果'],
['acorn_cooked','烤桦木果'],
['eggplant','茄子'],
['corn','玉米'],
['pumpkin','南瓜'],
['pomegranate','石榴'],
['durian','榴莲'],
['dragonfruit','火龙果'],
['watermelon','西瓜'],
['cactus_meat','仙人掌肉'],
['humanmeat','人肉？'],
['humanmeat _dried','人肉干？'],
['goatmilk','羊奶'],
['royal_jelly','蜂王浆'],
['saltstack','盐堆'],
['tacklestation','钓具容器'],
['trophyscale_fish','鱼类计重器'],
['mast','扬帆（基础版）'],
['mast_malbatross','扬帆（邪天翁版）'],
['fish_box','锡鱼桶'],
['seafaring_prototyper','智囊团（海洋科技）'],
['hotspring','温泉'],
['multiplayer_portal_moonrock','天空传送门（装修前）'],
['multiplayer_portalmoonrock_constr','天空传送门（装修后）'],
['campfirefire','篝火火苗（永不熄灭）'],
['coldfirefire','冷篝火火苗（永不熄灭）'],
['cartographydesk','制图师的桌子'],
['sculptingtable','陶轮'],
['chesspiece_pipe_marble（大理石的），chesspiece_pipe_stone（石头的）','泡沫管雕刻'],
['moondial','月盘'],
['diviningrodbase','探测杖底座'],
['wardrobe','衣柜'],
['endtable','茶几'],
['succulent_potted','盆栽多肉植物'],
['scarecrow','稻草人'],
['saltlick','盐碱地'],
['mushroom_light','蘑菇灯'],
['mushroom_light2','蘑菇灯2'],
['staffcoldlight','极光'],
['dragonflyfurnace','龙鳞火炉'],
['townportaltal','懒惰背弃者'],
['wall_moonrock','月亮石墙'],
['wall_moonrock_item','月亮石墙（可放置的）'],
['shadowmeteor','陨石'],
['moonbase','月石'],
['insanityrock','方尖碑']]
codebase = DataFrame(data,columns = ['code','CNname'])

def getname():
    global name
    name = input("输入要查询的关键词\n")
    name = list(name)

def searcher():
    #global paper
    paper = DataFrame([['',''],['',''],['',''],['',''],['',''],['',''],['',''],['',''],['',''],['','']],columns = ['Name','Code'])
    ct = 0
    for i in range(0,codebase.shape[0]-1):
        CN_name = codebase.loc[i,'CNname']
        CN_name_list = list(CN_name)
        for j in CN_name_list:
            for k in name:
                if j == k:
                    paper.loc[ct,'Name'] = CN_name
                    paper.loc[ct,'Code'] = codebase.loc[i,'code']
                    ct = ct+1
    if paper.iloc[0,0] != '':
        print(paper)
    else:
        print("Not Found!")

def searcher_adv():
    #global paper
    paper = DataFrame([['','']],columns = ['Name','Code'])
    ct = 0
    length=len(name)
    #print(length)
    for i in range(0,codebase.shape[0]-1):
        CN_name = codebase.loc[i,'CNname']
        CN_name_list = list(CN_name)
        flag = 0
        for j in name:
            if flag < length:
               for k in CN_name_list:
                   if j == k:
                       flag = flag+1
        if flag >= length:
            paper.loc[ct,'Name'] = CN_name
            paper.loc[ct,'Code'] = codebase.loc[i,'code']
            ct =ct+1
    if paper.iloc[0,0] != '':
        print(paper)
    else:
        print("Not Found!")

mod = 'C'
while (mod != 'A') and (mod != 'B'):
    print("请选择要使用的查找方法\n")
    mod = input("A:给我所有包含关键字的代码\nB:标准查找法\n")
if mod == 'A':
    while True:
        getname()
        searcher()   
if mod == 'B':
    while True:
        getname()
        searcher_adv()   